### ISSUE TITLE
Logo design ideas

### ISSUE THREAD

**Issue by nephros** [sailfishos-chum/sailfishos-chum-gui#132]
Playing around in Inkscape a bit with the intention to improve the very plain logo, I came up with the idea of replacing the U with a fish hook.

The image I found for doing this had a C-like appendage and a long stem, which after a bit of shuffling became this:

![sailfishos-chum-gu_hooki](https://user-images.githubusercontent.com/1863836/207297660-c7feaba8-0904-47f0-b2b2-d3900972263f.png)

Now obviously, the M is missing there - and having a fish hook and a missing m, well, M is for Moray, so the next step was this:

![sailfishos-chum-gu_hooki_m](https://user-images.githubusercontent.com/1863836/207297961-6fbb9d89-6574-4a72-aa84-641396f3326e.png)

which looks terrible because unfortunately my vector drawing skills are non-existent.

Still, I wanted to share this here in the hopes someone actually talented might pick up on it.

So find below the "final" SVG I have now, and if you like, please improve.

**Comment by nephros** [comment]
![Uploading sailfishos-chum-gu_hooki.svg…]()
![sailfishos-chum-gu_hooki_m2](https://user-images.githubusercontent.com/1863836/207298401-42fe5486-a351-4ad5-9a37-b6527451bb7a.png)

**Comment by Olf0** [comment]
Though I like the idea(s) a lot, after thinking about these for a while, I believe they are way too hard to decode.  The vast majority of SailfishOS users are not native English speakers, hence all those who have not explored the topic "fishing" will not even know that "Chum" is related to that.  Additionally the fishing hook has become hard to perceive as such due to its two attachments.  And I would not have managed to figure out that these attachments are meant to be read as the letters "reversed, copylefted **C**" and "**H**", the fishing hook as "**U**" and the worm as "**M**", without reading [your initial message](https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/132#issue-1493966932) twice.

In short, IMO this way too overloaded and near impossible to comprehend for most.

A simpler idea: Put the SailfishOS logo atop the word "CHUM" in [the existing logo](https://github.com/sailfishos-chum/sailfishos-chum-gui/blob/main/icons/sailfishos-chum-gui.svg).  I should still have it around somewhere, but as it is copyrighted by Jolla, and Thaodan received it for the SailfishOS afternoon at FrOSCon 2019 I organised, you might rather request it from Jolla again (they do allow for many SailfishOS-specific uses of this logo).  Furthermore it was a bitmap ("raster) icon, but it would be much better to obtain it in a vector graphic format (usually Adobe Illustrator `.ai` or SVG; do not be afraid of `.ai`-files, Inkscape handles them well and they are what customers usually receive from graphics design studios; i.e., Jolla might not have it as SVG and your contact may nor know that these two file formats are basically equivalent.  Idea to circumvent that: Ask @llewelld ("flypig" at FSO)).

BTW, this idea came, because I looked at [the Storeman logo](https://github.com/storeman-developers/harbour-storeman/blob/devel/icons/harbour-storeman.svg) (by [Laurent Chambon (Laurent_C)](https://mastodon.social/@Laurent_C)) quite often lately, which also incorporates the SailfishOS logo.

**Comment by Olf0** [comment]
I gave it a try, because I gained some experience with vector- and bitmap graphics handling and design on my real job in the past two years.  It all the same SVG, just with different layers visible: [sailfishos-chum_which-font-to-use.svg](https://user-images.githubusercontent.com/16547876/209615068-e94fd5b1-8120-4883-a4d4-7637e07bdc1c.svg)

The first three are a logo for SailfishOS:Chum in general, an icon for the SailfishOS:Chum GUI application and a version with the original text inserted:

![sailfishos-chum](https://user-images.githubusercontent.com/16547876/209614289-967a82d7-96f0-45d0-bfdc-8957b38116e6.png) ![sailfishos-chum-gui](https://user-images.githubusercontent.com/16547876/209614292-c2927aec-3af5-47cd-bec3-8ec9f8876e5c.png) ![sailfishos-chum_original-text](https://user-images.githubusercontent.com/16547876/209614293-e559e1af-f144-49f5-adb2-6c795177110a.png)

This one I generated to compare the fonts which seemed to be suitable (and close to the original glyphs):

![sailfishos-chum_which-font-to-use](https://user-images.githubusercontent.com/16547876/209615067-92c16903-9290-49dc-8477-a9dce29e362f.png)

The fonts I preselected, look almost the same, but none does exactly match the original font, which I do like a lot: Does anybody (@rinigus, @piggz) know which font that is, because separate glyph outlines were exported for each character (Adobe Illustrator does that by default), hence I have no chance to technically determine which font was originally used.  I ultimately used the font *System-ui*, but would gladly switch to the original font (if it carries a suitable license).

**Comment by Olf0** [comment]
Found how to convert font-glyphs to paths (quit simple, actually), e.g.: https://linuxhint.com/convert-text-to-path-inkscape/

I would be glad to receive some feedback, before I carry on finishing this.

**Comment by wheelseal** [comment]
> Though I like the idea(s) a lot, after thinking about these for a while, I believe they are way too hard to decode. The vast majority of SailfishOS users are not native English speakers, hence all those who have not explored the topic "fishing" will not even know that "Chum" is related to that. Additionally the fishing hook has become hard to perceive as such due to its two attachments. And I would not have managed to figure out that these attachments are meant to be read as the letters "reversed, copylefted **C**" and "**H**", the fishing hook as "**U**" and the worm as "**M**", without reading [your initial message](https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/132#issue-1493966932) twice.
> 
> In short, IMO this way too overloaded and near impossible to comprehend for most.
> 
> A simpler idea: Put the SailfishOS logo atop the word "CHUM" in [the existing logo](https://github.com/sailfishos-chum/sailfishos-chum-gui/blob/main/icons/sailfishos-chum-gui.svg). I should still have the SFOS-logo around somewhere, but as it is copyrighted by Jolla, and Thaodan received it for the SailfishOS afternoon at FrOSCon 2019 I organised, you might rather request it from Jolla again (they do allow for many SailfishOS-specific uses of this logo). Furthermore it was in a bitmap ("raster) format, but it would be much better to obtain it in a vector graphic format, usually Adobe Illustrator `.ai` or SVG; do not be afraid of `.ai`-files, Inkscape handles them well and they are what customers usually receive from graphics design studios, i.e., Jolla might not have it as SVG and your contact may nor know that these two file formats are basically equivalent. Idea to circumvent the latter: Ask @llewelld ("flypig" at FSO).
> 
> _Edit:_ I just found the SailfishOS logo as a vector graphic in SVG format, see https://sailfishos.org/content/uploads/2021/02/SF4.svg
> 
> BTW, I had this idea, because I looked at [the Storeman logo](https://github.com/storeman-developers/harbour-storeman/blob/devel/icons/harbour-storeman.svg) (by [Laurent Chambon (Laurent_C)](https://mastodon.social/@Laurent_C)) quite often lately, which also incorporates the SailfishOS logo.

I Agree with Olf0. It looks good but is too difficult to understand. I´m a German user and first I don´t understand it.

**Comment by wheelseal** [comment]
Do we need the words Chum GUI inside the logo? It is written under the logo. I have been thinking about a new logo and want to share it with you if it's ok:

![chum1](https://user-images.githubusercontent.com/61382908/211870973-0b37d183-eb7e-4fd4-a0e3-7f00834cc98b.svg) > ![chum2](https://user-images.githubusercontent.com/61382908/211871191-66beb7f2-7baa-4489-a0f0-264907eb2d0c.svg) > ![chum3](https://user-images.githubusercontent.com/61382908/211873089-41b9e77f-c452-4848-b8e2-e50a1ea642e0.svg) > ![chum4](https://user-images.githubusercontent.com/61382908/211873272-4d1b104d-9b18-48b3-8131-82270d1b3b55.svg) > ![chum5](https://user-images.githubusercontent.com/61382908/211873294-5e26e816-1ef3-4fd4-b2d0-2c4f82c1312a.svg) > ![chum7](https://user-images.githubusercontent.com/61382908/211878030-826ae26a-b61b-4131-b646-1db053dd6d2d.svg) > ![chum6](https://user-images.githubusercontent.com/61382908/211873313-083e886f-1100-4ed1-940f-a5fcfc473f3a.svg)

For the round logos I was inspired by a CD as a storage medium.

**Comment by piggz** [comment]
Out of the above, id vote for the 5th

**Comment by Olf0** [comment]
> Do we really need the words Chum GUI inside the logo?

Yes, because …

> It is written under the logo.

that is solely the case for the icon of an installed SailfishOS:Chum GUI application on SailfishOS-Desktop ("launcher").  I.e., even for the specific SailfishOS:Chum GUI application icon that is usually not true.  And we also need a separate icon for the SailfishOS:Chum community repository proper and the repo config RPM (one icon will do for both IMO).

This is why I created a "Chum" and a "Chum GUI" icon:
![sailfishos-chum](https://user-images.githubusercontent.com/16547876/209614289-967a82d7-96f0-45d0-bfdc-8957b38116e6.png) &nbsp; ![sailfishos-chum-gui](https://user-images.githubusercontent.com/16547876/209614292-c2927aec-3af5-47cd-bec3-8ec9f8876e5c.png)

**Comment by Olf0** [comment]
> Out of the above, id vote for the 5th

So do I.
The issue I see that there are too many too tiny elements (these two aspects correlate strongly) for a mobile screen: Take a look at this page on your mobile phone and look at the logos from your regular viewing distance: I can hardly recognise anything (No. 5 & 6 are also the best in this aspect).

If you want to pursue No. 5 @wheelseal, can you please try to significantly enlarge the Sailfish(OS logo), which requires to shorten the topmost streaks.  The size of the "app icons" is fine IMO, it might help to reduce their number to 4 or 5 in order to enlarge the Sailfish.  Please also make the Sailfish and the streaks a bit bolder, but not as bold as the Sailfish in No.6 (that is a bit too much, for me it already becomes harder to recognise, because it is slightly too bold).

**Comment by Olf0** [comment]
Here a pretty extreme example how recognisable icons have to be: Take a look at the source code repository icons at the lower left in the open browser tab (in 1920x1080 Px², I look at this on my 15" laptop screen).  The Patchmanager icon is hardly recognisable, the *current* SailfishOS:Chum icon is worse (I am not able to read "CHUM" there).

![Screenshot from 2023-01-11 22-24-35](https://user-images.githubusercontent.com/16547876/211921751-97fef742-1e95-44b9-b4df-35db7c2c1030.png)

**Comment by nephros** [comment]
Are we commited to the color scheme?

Here are some tries switching to another, in this case the gradients from "icon-launcher-system-update" from Jollas Apss icon library - and using the swirly logo from there while we're at it.

![sailfishos-chum-gui-light4](https://user-images.githubusercontent.com/1863836/212839755-ef6eda96-c391-453d-a6ec-ac6431000b8d.png),  ![sailfishos-chum-gui-light1](https://user-images.githubusercontent.com/1863836/212839761-49a9cdbe-e64e-4ca0-ab49-a00058f21310.png)
![sailfishos-chum-gui-light2](https://user-images.githubusercontent.com/1863836/212839766-6211d352-91b4-48f6-9e86-930cb106dd39.png),  ![sailfishos-chum-gui-light3](https://user-images.githubusercontent.com/1863836/212839774-f836c3ab-e9d4-4292-9724-a9529ff863be.png)

**Comment by nephros** [comment]
Using an image search I just came buy the rather "playful" and somehow very un-jolla-like logo for harbour:

https://harbour.jolla.com/assets/images/harbor-logo-8d610d8a7fce1c9f08c00bf78160a81e.png

So if the anchor-and-rope image is for harbour, chum could be hook-and-fishing line (or also rope) for its logo/banner.

**Comment by Olf0** [comment]
> Are we commited to the color scheme?

Not necessarily, such things are always tricky to find the right balance between continuity (of the old [icon]) and enhancements (which implicitly results in something new).  I assumed the dark greenish blue to represent water.

I am no so happy with strong gradients, because they decrease visibility. Light gradients are fine, but hard to perceive so they might be omitted. And what does a gradient represent?  But if it improves aesthetics and does not negatively affect any other aspect, a gradient is sure fine.

For the background, a strong gradient is even more problematic, as you can see above: it is "dissolving" the logo to the right into the white background of the web-page; the same will happen for "light ambiences" (IMO they are rather "bright").

> Here are some tries switching to another, in this case the gradients from "icon-launcher-system-update" from Jollas Apss icon library - and using the swirly logo from there while we're at it.

The old, "swirly" SailfishOS logo is a good example for over-designing IMO: I have seen it so many times since in 2014 and only today in the context of this logo discussion I comprehend that it also represents a sailfish!

WRT then old harbour logo (Jolla ceased using it long ago): Yes, a harbour as a anchoring place is common knowledge in contrast to a chum, hence the anchor is much easier to interpret for most.  But I never detected the rope as such. Furthermore it is a good example of a logo being too "un-contrasty", especially the white, broken letter stroke on a bright gray background.

**Comment by Olf0** [comment]
I tried to play with a background gradient, as I liked the idea.  I am nor really satisfied, but maybe the start- and end-colour of the gradient are just not well chosen:

![sailfishos-chum_visible_v3](https://user-images.githubusercontent.com/16547876/212980290-27634c21-637f-4188-8924-09b596556db0.svg) &nbsp; ![sailfishos-chum-gui_visible_v3](https://user-images.githubusercontent.com/16547876/212980281-23466972-5041-46af-afcc-37ae01a38026.svg)

The text position are shifted to the left, because I have not exported them as individual glyphs, yet.

**Comment by Olf0** [comment]
I continued to play with it:
- I was not able to find any better start- and end-colour for the background-gradient.  If someone has a suggestion, just name them as "HTML-colours" (six digit hex numbers).
- I was dissatisfied with the contrast of the letters, so I experimented with darkening them and using black and white outlines (as already with the sailfish):

![sailfishos-chum_visible_v3+darker](https://user-images.githubusercontent.com/16547876/213299745-d3529577-39e4-44e4-b11f-d2a3ffa30652.svg) &nbsp;![sailfishos-chum_visible_v3+much-darker](https://user-images.githubusercontent.com/16547876/213299775-643371d1-0360-4e42-838a-ce6eb22bbc1d.svg) &nbsp;![sailfishos-chum_visible_v3+black](https://user-images.githubusercontent.com/16547876/213299801-333678c0-11aa-46a5-9c48-caaae640cc87.svg) &nbsp;![sailfishos-chum_visible_v3+white](https://user-images.githubusercontent.com/16547876/213299834-b8eb0382-d11e-4326-a1dd-0c1a00009aa4.svg) &nbsp;![sailfishos-chum_visible_v3+black-outline](https://user-images.githubusercontent.com/16547876/213299851-e69cb6a3-146d-43ec-98d3-256807428acb.svg) &nbsp;![sailfishos-chum_visible_v3+white-outline](https://user-images.githubusercontent.com/16547876/213299870-2b295cc3-69bd-4426-b509-1943db32c503.svg)

While it is impressive how different the same colour inside a black or white outline looks, the outlined versions do not look good IMO, when small.  And the fully black glyphs are just too black from my POV.
The remaining three ("darker glyphs", "much darker glyphs" and "white glyphs" are O.K. IMO, I like the first one best.

Opinions?

**Comment by piggz** [comment]
Of the above, no4 ... could the graphic be simpler? with the outline it looks a little busy

**Comment by Olf0** [comment]
> Of the above, no4 ... could the graphic be simpler? with the outline it looks a little busy

The outline *is* "the graphic", i.e., the SailfishOS logo since 2016.  I can fill it with whatever colour, transparency (100% in the original, so the background shines fully through; see all former examples from all tree of us) or a mix of these two.  I can also set then outline colour, but only white and black do work well.  Or its width, which I increased by a factor of ~ 1,25 to enhance visibility (idea "stolen" from @wheelseal).
But to do away with the outline results in having four strangely shaped patches hovering above the glyphs / letters.

What I do like is to give the body of the sailfish a different colour than the background, because it looks more than a sailfish than a logo, then.  Hence I used the background colour of the original, first SailfishOS:Chum icon to colour then fish.

**Comment by piggz** [comment]
![chum](https://user-images.githubusercontent.com/4650063/213532333-aa05c8b3-51fd-4383-82e7-ab88e0918027.png)
Something i knocked up

**Comment by llewelld** [comment]
> Jolla might not have it as SVG and your contact may nor know that these two file formats are basically equivalent. Idea to circumvent the latter: Ask @llewelld ("flypig" at FSO).

Sorry for not replying earlier and thanks for your prod via the forum @Olf0. There's a lovely variety of icons here. Since @Olf0 asked if there's a licence (or convention) for using the Sailfish OS logo in app icon designs, I've asked about it internally and will get back here when I find out.

You already found an SVG of the Sailfish OS logo, but for completeness and future reference, it's also available on the [Press page](https://jolla.com/press/) (scroll to the bottom of the page). The PDF version is in vector format and can be converted to SVG.

Finally, I didn't see mention of the [App Icons Story and Template](https://sailfishos.org/design/icons/) here. You should have your icon design however you want of course, but personally I prefer a launcher where all the icons broadly follow the guidelines (e.g. padding dimensions) described there and it's definitely worth a look.

**Comment by Olf0** [comment]
[\@marbalf](https://forum.sailfishos.org/u/marbalf) contributed this:
> I am sending you an icon I made for me some time ago. I hadn’t realised that there had been a discussion and some proposals about icons already.
> 
> Feel free to comment on it, dump it, adopt it, or adapt it.

![547bfa4786bff577538e09e54af59ec54fc195b3](https://user-images.githubusercontent.com/16547876/218117702-9fca570b-82d7-4410-9b92-3dd585d1c970.png)

**Comment by wheelseal** [comment]
> If you want to pursue No. 5 @wheelseal, can you please try to significantly enlarge the Sailfish(OS logo), which requires to shorten the topmost streaks. The size of the "app icons" is fine IMO, it may help to reduce their number to 4 or 5 in order to enlarge the Sailfish. Please also make the Sailfish and the streaks a bit bolder, but not as bold as the Sailfish in No. 6 (that is a bit too much, for me it already becomes harder to recognise, because it is slightly too bold).
> Side note: The "app icons" do not have to be slightly scattered (but sure can), they also look fine if strongly ordered, as in No. 6. They may even look better ordered, but I would have to see a scattered variant (No. 5) with an ordered one having the same outline as No. 5 side-by-side to come up with a clear preference.

![chum5 2](https://user-images.githubusercontent.com/61382908/221878178-b313f469-33ea-4d0c-9560-ef4d91ea2a12.svg)>>   ![chum5 2 ordered](https://user-images.githubusercontent.com/61382908/221878727-bcb0716e-dc1d-4182-bf9f-71f42a692110.svg)

Sorry for my late reply. Left is the original (Nr. 5) and on the right a reordered version. I also deleted the gradient from the lines because if i opened it in the browser the gradients are shown as black lines.

**Comment by Olf0** [comment]
@wheelseal, thank you for your feedback.

Yes, number 4 was added later.  It was an experiment to hear from piggz if he meant that.  It was a failure.

Your comments helped me understand, that perception differs a lot: For example [the black letters in the third icon here](https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/132#issuecomment-1396123387) are outright ugly IMO.

> By the way: If I tap on every SVGs uploaded here (your and mine) The Preview in Firefox is Black.

Firefox's SVG renderer was always weak.  This is why GitHub renders them independently.

**Comment by Olf0** [comment]
weelseal's comment made me rereading this thread:
* Only his and my designs are technically usable, all others are not SVGs.
* His designs do not obey the keep out area ("padding area") as flypig indicated.  See the designs from piggz and marbalf, which make this area explicit by shading it differently and [page 10 of Jolla's *App icon story* PDF](https://sailfishos.org/content/uploads/2018/11/48_SAILFISH-APPS-ICON-STORY.pdf).

I think we all spent too much time at this (for me I can say that for sure) and my tried to gather conclusive opinions on specific designs mostly failed.  I will see what to make out of this, as there seems to be no common understanding of a constructive process towards a logo which fulfils the basic design criteria by Jolla, technical necessities and readability necessities.

Thank you all for you ideas and feedback.
