### ISSUE TITLE
[Suggestion] Prepare to deal with `sailfishos/ssu` PR #16

### ISSUE THREAD

**Issue by nephros** [sailfishos-chum/sailfishos-chum-gui#270]
#### DESCRIPTION

An unannounced and unreleased Sailfish OS version ("4.6") will change the way versions are handled in the `ssu` utility.

I imagine this may have an impact on how Chum GUI handles/must handle OBS repository information, hence this issue.

#### ADDITIONAL INFORMATION

- https://github.com/sailfishos/ssu/pull/16
- https://irclogs.sailfishos.org/logs/%23sailfishos/%23sailfishos.2024-04-11.log.html

**Comment by Olf0** [comment]
See also https://github.com/sailfishos-chum/sailfishos-chum-gui-installer/issues/39, https://github.com/storeman-developers/harbour-storeman-installer/issues/308 and https://github.com/storeman-developers/harbour-storeman/issues/488.

Please use https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/270 (i.e. this issue) as the main, tracking issue for this.

**Comment by Olf0** [comment]
1. Thank you for the heads up, @nephros.
2. On first sight, [`sailfishos/ssu#16`](https://github.com/sailfishos/ssu/pull/16) looks like a backward compatible change to me.  I may have missed something, but the wording of the PR title ("Add … variables"), its description ("Allows using …") and [Keto's IRC chat message](https://irclogs.sailfishos.org/logs/%23sailfishos/%23sailfishos.2024-04-11.log.html#t2024-04-11T18:20:01) ("… can be used …") supports my impression (actually such wording would be hideous, if something is changed in a non-backward compatible way).
3. I am a little more afraid about the depicted change for SailfishOS 5.0.0, but I may read too much into the wording ["… 5.0 we will cut down the full version down to 3 segments"](https://irclogs.sailfishos.org/logs/%23sailfishos/%23sailfishos.2024-04-11.log.html#t2024-04-11T18:22:19).  Maybe the full version string will be still available, retrievable and usable, so extant software does not need to be altered.
4. If any of these changes turns out to break software, I must clearly state that I am so sick of it: Despite Sailor reiteration how "valuable" the community is, we are mostly still treated as beta testing monkeys and specifically Jolla / Jollyboys could not care less about the developer community.  All the mostly unnecessary breaking changes in the past rendered so much software by community developers dysfunctional, resulting in significantly less working software, though most components of SailfishOS support backward compatibility very well (e.g. Qt / QML).  But breaking changes continue to be introduced, still the completely outdated, long unsupported Qt 5.6 stays!  Furthermore this perpetual flow of breaking changes causes so much frustration among users (software does not work after upgrade, and stays this way if unmaintained) and developers (Sailors steal my spare time again and again for adapting the breaking changes they create during their paid working hours; I cannot work on enhancing my software, because Sailors keep me busy with fixing the stuff they break).  I addressed this many times, [here the last time](https://github.com/storeman-developers/harbour-storeman/issues/461#issuecomment-1997824451).
5. Consequently I strongly believe, if any of these changes break backward compatibility, this is an excellent chance to confront Jolla with the consequences: No working SailfishOS:Chum-GUI app, no working SailfishOS:Chum-GUI-Installer and Storeman-Installer and no working Storeman self-update.  We must leave it this way for at least a month after the GA (general availability) release (i.e. the EA release does not count, because too few users are affected).  Maybe then Jolla finally realises that the Jolla Store has become a bad joke long ago, that SailfishOS users do depend on OpenRepos and SailfishOS:Chum, and ultimately that community developers are a crucial part of the SailfishOS ecosystem, hence Jolla cannot do without them.  Thus I am asking everybody to do nothing until things break and then take their due time to analyse the situation thoroughly, followed by designing, discussing with everyone involved, lastly implementing and testing an adaption to the breaking changes: I am sure this process takes a double-digit number of weeks, starting with the EA release date.  I have to add that Jolla's breaking changes caused so much work and frustration for me over the years that I am neither willing or able to (due to alack of energy) quickly adapt the software I am maintaining to their negligence, again and again.

**Comment by Olf0** [comment]
See also issue #287.
