### ISSUE TITLE
gh-pages: URLs should be from sailfishos:chum

### ISSUE THREAD

**Issue by rinigus** [sailfishos-chum/sailfishos-chum-gui#4]
Depends on #1 

https://sailfishos-chum.github.io/sailfishos-chum-gui/ should pull data from `sailfishos:chum` and not the `testing` sub-repo. But we need GUI to be released in some form first

**Comment by mentaljam** [comment]
You are definitely right. I uploaded this page here for demonstration only. Maybe we need to find a better place for it if the community found it usefull?)

**Comment by mentaljam** [comment]
I have created a netlify app for RPM selection https://chumrpm.netlify.app/. I switched the selection logic to a serverless function which has a couple of advantages:

- no need in a CORS proxy to get OBS repository files,
- a global cache for repositories on the function-side which reduces the number of requests.

So I want to ask for a new repository for the code. Not sure about the name. Maybe sailfishos-chum-web? Because maybe someone will improve the HTML/CSS part and we get a full-fledged website.

**Comment by rinigus** [comment]
Great! Repo is done and your invite should be in the mailbox.

**Comment by Olf0** [comment]
May be a little RPM based on the "[Storeman Installer](https://github.com/mentaljam/harbour-storeman-installer)" (when it is working well) might be a lot easier to use:
It could determine the variables, download and install both packages in one go, without any extra clicking etc.

**Comment by mentaljam** [comment]
Maybe as an addition to the web installer as it is more universal as I think

**Comment by Olf0** [comment]
BTW, https://sailfishos-chum.github.io/sailfishos-chum-gui/ yields a "404 - Not found!", and so does https://sailfishos-chum.github.io/
AFAIU solely https://chumrpm.netlify.app/ is the recent user-oriented web-page for SailfishOS:Chum

If my observation is correct, there is nothing to do and this is just documenting this fact.
If not, please rectify my statements above.  I looked a `ghpages` (or similar) subdirectory in [the three SailfishOS:Chum-repositories](https://github.com/sailfishos-chum) to no avail, but I cannot look into the repo configuration to assure the GitHub-pages are switched off for all three repos.
